import Header from "@/components/Header";
import "../styles/main.scss";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <main className="">
          {/* <Header /> */}
          {children}
        </main>
      </body>
    </html>
  );
}
