import Header from "@/components/Header";
import "../styles/main.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Header />
        <main className="mt-14 py-8 px-6 max-w-7xl mx-auto  md:px-8  2xl:max-w-7xl">
          {children}
        </main>
      </body>
    </html>
  );
}
